site_name: Sams Pages
site_description: Documentation for People


theme:
    name: material
    logo: images/Fox.png
    favicon: images/test.ico
    features:
        - navigation.footer
        - content.code.copy
        - content.code.select
        - content.code.annotate
    palette:
        # Dark Mode
        - scheme: slate
          toggle:
            icon: material/weather-sunny
            name: Dark Mode
          primary: purple
          accent: lime
        
        # Light Mode
        - scheme: default
          toggle:
            icon: material/weather-night
            name: Light Mode
          primary: orange
          accent: blue

     
markdown_extensions:
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.inlinehilite
    - pymdownx.critic
    - pymdownx.snippets
    - pymdownx.keys:
    - pymdownx.superfences:
    - pymdownx.tabbed:
        alternate_style: true 
    - admonition
    - pymdownx.details    
    
    
    
copyright: Copyright &copy; 2025 VEDI Labs
